# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
# 打包准备：修改version number 和 build number

	def prepare_version(options)

    	increment_version_number(
        	version_number: options[:version]
    	)

    	increment_build_number(
        	build_number: options[:build]
    	)

	end





  desc "打debug环境ipa"

  lane :build_debug do |options|
	
	desc "清除 derived data"
	clear_derived_data

	desc "修改version和build number"
	prepare_version(options)
   
	desc "修改team"
	update_project_team(path: "AudioRecordAndCrop.xcodeproj",
                  teamid: "ZAJF5TDZCS")


  	desc "创建ipa"
  	gym(
		output_name:"debug",
		clean:true,
		configuration: "Debug",
    		scheme:"AudioRecordAndCrop",
	  	export_method:"development",
		output_directory:"IPA"
	)
  	end

end
